version: '3.8'

services:
  # Frontend - Next.js Development Server
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - vibe-network

  # Backend - FastAPI Development Server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://vibe_user:vibe_password@postgres:5432/vibe_invoice_db
      - PYTHONPATH=/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - vibe-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=vibe_invoice_db
      - POSTGRES_USER=vibe_user
      - POSTGRES_PASSWORD=vibe_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vibe-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vibe_user -d vibe_invoice_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Adminer - Database Administration
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - vibe-network

volumes:
  postgres_data:

networks:
  vibe-network:
    driver: bridge